/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
 * OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0>.
 */

/** @file orders_ffi.h Canonical order, shared-list and timetable owners. */
#ifndef RUST_ORDERS_FFI_H
#define RUST_ORDERS_FFI_H
#include <cstddef>
#include <cstdint>
struct OpenTTDOrderFields {
	uint8_t type, flags;
	uint16_t destination;
	uint8_t refit_cargo;
	uint16_t wait_time, travel_time, max_speed;
};
struct OpenTTDConsistState {
	int32_t current_order_time, lateness_counter;
	uint64_t timetable_start, last_departure, next_departure;
	int32_t round_trip_time;
	uint8_t real_index, implicit_index;
	uint16_t vehicle_flags;
};
struct OpenTTDVehicleOrderState {
	OpenTTDOrderFields current;
	void *orders, *next_shared, *previous_shared;
};
struct OpenTTDOrderListState {
	uint8_t manual;
	uint32_t vehicles;
	void *first_shared;
	int32_t timetable_duration, total_duration;
};
struct OpenTTDOrderBackupState {
	uint32_t user, tile;
	uint16_t group;
	const void *clone;
};
struct OpenTTDOrderVector;
struct OpenTTDOrdersClosest { uint32_t tile; uint16_t destination; uint8_t reverse, found; };
/* Immutable typed service table, borrowed synchronously without copying.
 * Services terminate on escaping exceptions; Rust borrows end before callbacks. */
struct OpenTTDOrdersLeaves {
	OpenTTDVehicleOrderState *(*vehicle)(void *) noexcept;
	OpenTTDConsistState *(*consist)(void *) noexcept;
	OpenTTDOrderListState *(*list)(void *) noexcept;
	OpenTTDOrderVector *(*vector)(void *) noexcept;
	OpenTTDOrderBackupState *(*backup)(void *) noexcept;
	OpenTTDOrderVector *(*backup_vector)(void *) noexcept;
	OpenTTDConsistState *(*backup_consist)(void *) noexcept;
	void *(*first_vehicle)(void *ctx) noexcept;
	uint64_t (*last_station)(void *ctx) noexcept;
	uint64_t (*ownerless_station)(uint16_t station, uint8_t if_valid) noexcept;
	uint64_t (*vehicle_type)(void *ctx) noexcept;
	uint64_t (*vehicle_status)(void *ctx) noexcept;
	uint64_t (*tick_counter)() noexcept;
	uint64_t (*primary_vehicle)(void *ctx) noexcept;
	uint64_t (*vehicle_ownership)(void *ctx, void *result) noexcept;
	uint64_t (*ticks_per_second)() noexcept;
	uint64_t (*unit_number)(void *ctx) noexcept;
	uint64_t (*economy_date)() noexcept;
	uint64_t (*economy_fraction)() noexcept;
	uint64_t (*maximum_date)() noexcept;
	uint64_t (*timetable_year_limit)() noexcept;
	uint64_t (*stopped_or_crashed)(void *ctx) noexcept;
	void *(*allocate_list)() noexcept;
	uint64_t (*suppress_implicit)(void *ctx) noexcept;
	uint64_t (*shared_window)(void *ctx, void *first) noexcept;
	uint64_t (*vehicle_id)(void *ctx) noexcept;
	uint64_t (*percent_filled)(void *ctx) noexcept;
	uint64_t (*reliability)(void *ctx) noexcept;
	uint64_t (*engine_reliability)(void *ctx) noexcept;
	uint64_t (*display_speed)(void *ctx) noexcept;
	uint64_t (*age_years)(void *ctx) noexcept;
	uint64_t (*needs_service)(void *ctx) noexcept;
	uint64_t (*remaining_years)(void *ctx) noexcept;
	uint64_t (*airport_tile)(uint16_t destination) noexcept;
	uint64_t (*base_station_tile)(uint16_t destination) noexcept;
	uint64_t (*station_tile)(uint16_t destination) noexcept;
	uint64_t (*depot_tile)(uint16_t destination) noexcept;
	uint64_t (*distance)(uint32_t first, uint32_t second, uint8_t square) noexcept;
	uint64_t (*station_location)(void *ctx, uint16_t destination) noexcept;
	uint64_t (*destination_tile)(void *ctx) noexcept;
	uint64_t (*aircraft_flying)(void *ctx) noexcept;
	uint64_t (*target_airport)(void *ctx) noexcept;
	uint64_t (*waypoint_tile)(uint16_t destination) noexcept;
	uint64_t (*at_station)(void *ctx) noexcept;
	uint64_t (*tile_station)(void *ctx) noexcept;
	uint64_t (*ship_station_tile)(uint16_t destination) noexcept;
	uint64_t (*valid_station)(uint16_t destination) noexcept;
	uint64_t (*station_owner)(uint16_t destination) noexcept;
	uint64_t (*can_use_station)(void *ctx, uint16_t destination) noexcept;
	uint64_t (*owner_check)(uint8_t owner, void *result) noexcept;
	uint64_t (*station_error)(void *ctx, uint16_t destination) noexcept;
	uint64_t (*has_hangar)(uint16_t destination) noexcept;
	uint64_t (*valid_depot)(uint16_t destination) noexcept;
	uint64_t (*depot_owner)(uint16_t destination) noexcept;
	uint64_t (*rail_depot)(uint16_t destination) noexcept;
	uint64_t (*road_depot)(uint16_t destination) noexcept;
	uint64_t (*ship_depot)(uint16_t destination) noexcept;
	uint64_t (*valid_waypoint)(uint16_t destination) noexcept;
	uint64_t (*waypoint_facilities)(uint16_t destination) noexcept;
	uint64_t (*waypoint_owner)(uint16_t destination) noexcept;
	uint64_t (*list_capacity)() noexcept;
	void *(*next_backup)(uint32_t first) noexcept;
	void *(*next_vehicle)(uint32_t first) noexcept;
	uint64_t (*aircraft_range)(void *ctx) noexcept;
	uint64_t (*aircraft_range_square)(void *ctx) noexcept;
	uint64_t (*bus)(void *ctx) noexcept;
	uint64_t (*backup_capacity)() noexcept;
	void *(*create_backup)(void *ctx, uint32_t user) noexcept;
	uint64_t (*networking)() noexcept;
	uint64_t (*network_server)() noexcept;
	uint64_t (*network_client)() noexcept;
	uint64_t (*server_client)() noexcept;
	uint64_t (*default_group)() noexcept;
	uint64_t (*vehicle_tile)(void *ctx) noexcept;
	uint64_t (*vehicle_group)(void *ctx) noexcept;
	uint64_t (*unique_backup_name)(void *ctx) noexcept;
	uint64_t (*backup_id)(void *ctx) noexcept;
	uint64_t (*backup_hangar)(void *ctx) noexcept;
	uint64_t (*review_setting)() noexcept;
	uint64_t (*local_owner)(void *ctx) noexcept;
	uint64_t (*day_counter)(void *ctx) noexcept;
	uint64_t (*fast_aircraft)(void *ctx) noexcept;
	uint64_t (*short_strip)(uint16_t destination) noexcept;
	uint64_t (*no_jet_crash)() noexcept;
	void (*append_station)(void *ctx, uint16_t station) noexcept;
	void (*invalidate_station_list)() noexcept;
	void (*command_error)(void *ctx, uint32_t error, uint32_t detail) noexcept;
	void (*timetable_dirty)(void *ctx) noexcept;
	void (*invalidate_order)(void *ctx, int32_t data) noexcept;
	void (*vehicle_dirty)(void *ctx) noexcept;
	void (*delete_order_news)(void *ctx) noexcept;
	void (*suppress_implicit_write)(void *ctx, uint8_t suppress) noexcept;
	void (*invalidate_vehicle_list)(void *ctx) noexcept;
	void (*close_shared_window)(void *ctx, uint32_t window) noexcept;
	void (*invalidate_shared_window)(void *ctx, uint32_t window, int32_t data) noexcept;
	void (*last_station_write)(void *ctx, uint16_t station) noexcept;
	void (*dirty_vehicle_windows)(void *ctx) noexcept;
	void (*capture_backup_metadata)(void *ctx, void *source) noexcept;
	void (*clear_backup_name)(void *ctx) noexcept;
	void (*restore_backup_metadata)(void *ctx, void *backup) noexcept;
	void (*order_news)(void *ctx, uint32_t message) noexcept;
	void (*debug_list)(void *ctx) noexcept;
	void (*assert_departure_range)(int32_t lower, int32_t upper) noexcept;
	void (*delete_list)(void *ctx) noexcept;
	void (*leave_station)(void *ctx) noexcept;
	void (*reverse_train)(void *ctx) noexcept;
	void (*next_airport)(void *ctx) noexcept;
	void (*set_destination)(void *ctx, uint32_t tile) noexcept;
	void (*closest_depot)(void *ctx, OpenTTDOrdersClosest *result) noexcept;
	void (*share_command)(void *ctx, const void *source) noexcept;
	void (*group_command)(void *ctx, uint16_t group) noexcept;
	void (*delete_backup)(void *ctx) noexcept;
	void (*clear_backup_gui)(uint32_t tile, uint32_t user) noexcept;
	void (*clear_backup_post)(uint32_t user) noexcept;
	void (*missing_aircraft_orders)(void *ctx) noexcept;
	void (*change_timetable_command)(void *ctx, uint8_t index, uint8_t field, uint16_t value) noexcept;
};
extern "C" {
uint32_t openttd_rust_list_init(void *, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_recalculate(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_free(void *, uint8_t, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_decision(void *, uint8_t, uint32_t, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_stopping(void *, void *, uint8_t, uint32_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_insert(void *, uint32_t, const void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_delete(void *, uint32_t, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_move(void *, uint8_t, uint8_t, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_remove_vehicle(void *, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_list_complete(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_update_real(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_skip_real(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_increment_implicit(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_increment_real(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_has_depot(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_has_full_load(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_has_conditional(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_has_unbunching(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_leave_unbunching(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_wait_unbunching(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_measure_unbunching(void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_order_free(void *);
uint32_t openttd_rust_order_station(void *, uint16_t);
uint32_t openttd_rust_order_depot(void *, uint16_t, uint8_t, uint8_t, uint16_t);
uint32_t openttd_rust_order_waypoint(void *, uint16_t);
uint32_t openttd_rust_order_loading(void *, uint8_t);
uint32_t openttd_rust_order_leave(void *);
uint32_t openttd_rust_order_dummy(void *);
uint32_t openttd_rust_order_conditional(void *, uint8_t);
uint32_t openttd_rust_order_implicit(void *, uint16_t);
uint32_t openttd_rust_order_refit(void *, uint8_t);
uint32_t openttd_rust_order_equals(void *, const void *);
uint32_t openttd_rust_order_assign(void *, const void *);
uint32_t openttd_rust_order_convert(void *);
uint32_t openttd_rust_order_can_load_unload(void *);
uint32_t openttd_rust_order_can_leave(void *, uint8_t);
uint32_t openttd_rust_order_should_stop(void *, uint16_t, uint16_t);
uint32_t openttd_rust_timetable_change(void *, uint8_t, uint8_t, uint8_t, uint16_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_timetable_validate_bulk(void *, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_timetable_on_time(void *, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_timetable_start(void *, uint8_t, uint8_t, uint64_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_timetable_autofill(void *, uint8_t, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint32_t openttd_rust_timetable_update(void *, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_insert_order(void *, uint8_t, const void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_delete_order(void *, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_move_order(void *, uint8_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_delete_vehicle_orders(void *, uint8_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_add_shared(void *, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_remove_shared(void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_delete_implicit(void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_timetable_bulk(void *, uint8_t, uint16_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_order_destination(void *, int32_t, uint8_t, const void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_process_orders(void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_order_condition(void *, const void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_order_location(void *, uint8_t, const void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_order_distance(void *, uint8_t, uint8_t, int32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_insert(void *, uint8_t, uint8_t, const void *, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_delete(void *, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_skip(void *, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_move(void *, uint8_t, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_modify(void *, uint8_t, uint8_t, uint16_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_refit(void *, uint8_t, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_clone(void *, void *, uint8_t, uint8_t, void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_capture_backup(void *, const void *, uint32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_create(void *, uint32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_restore(void *, uint32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_clear_user(uint32_t, uint32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_reset(uint32_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_tile_clear(uint32_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_group_clear(uint16_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_vehicle_clear(void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_backup_destination_clear(uint8_t, uint16_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_command_clear_backup(uint32_t, uint32_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_remove_destination(uint8_t, uint16_t, uint8_t, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_check_orders(void *, const OpenTTDOrdersLeaves *);
uint64_t openttd_rust_begin_loading(void *, const OpenTTDOrdersLeaves *);
void *openttd_orders_first_vehicle(void *ctx) noexcept;
uint64_t openttd_orders_last_station(void *ctx) noexcept;
uint64_t openttd_orders_ownerless_station(uint16_t station, uint8_t if_valid) noexcept;
uint64_t openttd_orders_vehicle_type(void *ctx) noexcept;
uint64_t openttd_orders_vehicle_status(void *ctx) noexcept;
uint64_t openttd_orders_tick_counter() noexcept;
uint64_t openttd_orders_primary_vehicle(void *ctx) noexcept;
uint64_t openttd_orders_vehicle_ownership(void *ctx, void *result) noexcept;
uint64_t openttd_orders_ticks_per_second() noexcept;
uint64_t openttd_orders_unit_number(void *ctx) noexcept;
uint64_t openttd_orders_economy_date() noexcept;
uint64_t openttd_orders_economy_fraction() noexcept;
uint64_t openttd_orders_maximum_date() noexcept;
uint64_t openttd_orders_timetable_year_limit() noexcept;
uint64_t openttd_orders_stopped_or_crashed(void *ctx) noexcept;
void *openttd_orders_allocate_list() noexcept;
uint64_t openttd_orders_suppress_implicit(void *ctx) noexcept;
uint64_t openttd_orders_shared_window(void *ctx, void *first) noexcept;
uint64_t openttd_orders_vehicle_id(void *ctx) noexcept;
uint64_t openttd_orders_percent_filled(void *ctx) noexcept;
uint64_t openttd_orders_reliability(void *ctx) noexcept;
uint64_t openttd_orders_engine_reliability(void *ctx) noexcept;
uint64_t openttd_orders_display_speed(void *ctx) noexcept;
uint64_t openttd_orders_age_years(void *ctx) noexcept;
uint64_t openttd_orders_needs_service(void *ctx) noexcept;
uint64_t openttd_orders_remaining_years(void *ctx) noexcept;
uint64_t openttd_orders_airport_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_base_station_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_station_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_depot_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_distance(uint32_t first, uint32_t second, uint8_t square) noexcept;
uint64_t openttd_orders_station_location(void *ctx, uint16_t destination) noexcept;
uint64_t openttd_orders_destination_tile(void *ctx) noexcept;
uint64_t openttd_orders_aircraft_flying(void *ctx) noexcept;
uint64_t openttd_orders_target_airport(void *ctx) noexcept;
uint64_t openttd_orders_waypoint_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_at_station(void *ctx) noexcept;
uint64_t openttd_orders_tile_station(void *ctx) noexcept;
uint64_t openttd_orders_ship_station_tile(uint16_t destination) noexcept;
uint64_t openttd_orders_valid_station(uint16_t destination) noexcept;
uint64_t openttd_orders_station_owner(uint16_t destination) noexcept;
uint64_t openttd_orders_can_use_station(void *ctx, uint16_t destination) noexcept;
uint64_t openttd_orders_owner_check(uint8_t owner, void *result) noexcept;
uint64_t openttd_orders_station_error(void *ctx, uint16_t destination) noexcept;
uint64_t openttd_orders_has_hangar(uint16_t destination) noexcept;
uint64_t openttd_orders_valid_depot(uint16_t destination) noexcept;
uint64_t openttd_orders_depot_owner(uint16_t destination) noexcept;
uint64_t openttd_orders_rail_depot(uint16_t destination) noexcept;
uint64_t openttd_orders_road_depot(uint16_t destination) noexcept;
uint64_t openttd_orders_ship_depot(uint16_t destination) noexcept;
uint64_t openttd_orders_valid_waypoint(uint16_t destination) noexcept;
uint64_t openttd_orders_waypoint_facilities(uint16_t destination) noexcept;
uint64_t openttd_orders_waypoint_owner(uint16_t destination) noexcept;
uint64_t openttd_orders_list_capacity() noexcept;
void *openttd_orders_next_backup(uint32_t first) noexcept;
void *openttd_orders_next_vehicle(uint32_t first) noexcept;
uint64_t openttd_orders_aircraft_range(void *ctx) noexcept;
uint64_t openttd_orders_aircraft_range_square(void *ctx) noexcept;
uint64_t openttd_orders_bus(void *ctx) noexcept;
uint64_t openttd_orders_backup_capacity() noexcept;
void *openttd_orders_create_backup(void *ctx, uint32_t user) noexcept;
uint64_t openttd_orders_networking() noexcept;
uint64_t openttd_orders_network_server() noexcept;
uint64_t openttd_orders_network_client() noexcept;
uint64_t openttd_orders_server_client() noexcept;
uint64_t openttd_orders_default_group() noexcept;
uint64_t openttd_orders_vehicle_tile(void *ctx) noexcept;
uint64_t openttd_orders_vehicle_group(void *ctx) noexcept;
uint64_t openttd_orders_unique_backup_name(void *ctx) noexcept;
uint64_t openttd_orders_backup_id(void *ctx) noexcept;
uint64_t openttd_orders_backup_hangar(void *ctx) noexcept;
uint64_t openttd_orders_review_setting() noexcept;
uint64_t openttd_orders_local_owner(void *ctx) noexcept;
uint64_t openttd_orders_day_counter(void *ctx) noexcept;
uint64_t openttd_orders_fast_aircraft(void *ctx) noexcept;
uint64_t openttd_orders_short_strip(uint16_t destination) noexcept;
uint64_t openttd_orders_no_jet_crash() noexcept;
void openttd_orders_append_station(void *ctx, uint16_t station) noexcept;
void openttd_orders_invalidate_station_list() noexcept;
void openttd_orders_command_error(void *ctx, uint32_t error, uint32_t detail) noexcept;
void openttd_orders_timetable_dirty(void *ctx) noexcept;
void openttd_orders_invalidate_order(void *ctx, int32_t data) noexcept;
void openttd_orders_vehicle_dirty(void *ctx) noexcept;
void openttd_orders_delete_order_news(void *ctx) noexcept;
void openttd_orders_suppress_implicit_write(void *ctx, uint8_t suppress) noexcept;
void openttd_orders_invalidate_vehicle_list(void *ctx) noexcept;
void openttd_orders_close_shared_window(void *ctx, uint32_t window) noexcept;
void openttd_orders_invalidate_shared_window(void *ctx, uint32_t window, int32_t data) noexcept;
void openttd_orders_last_station_write(void *ctx, uint16_t station) noexcept;
void openttd_orders_dirty_vehicle_windows(void *ctx) noexcept;
void openttd_orders_capture_backup_metadata(void *ctx, void *source) noexcept;
void openttd_orders_clear_backup_name(void *ctx) noexcept;
void openttd_orders_restore_backup_metadata(void *ctx, void *backup) noexcept;
void openttd_orders_order_news(void *ctx, uint32_t message) noexcept;
void openttd_orders_debug_list(void *ctx) noexcept;
void openttd_orders_assert_departure_range(int32_t lower, int32_t upper) noexcept;
void openttd_orders_delete_list(void *ctx) noexcept;
void openttd_orders_leave_station(void *ctx) noexcept;
void openttd_orders_reverse_train(void *ctx) noexcept;
void openttd_orders_next_airport(void *ctx) noexcept;
void openttd_orders_set_destination(void *ctx, uint32_t tile) noexcept;
void openttd_orders_closest_depot(void *ctx, OpenTTDOrdersClosest *result) noexcept;
void openttd_orders_share_command(void *ctx, const void *source) noexcept;
void openttd_orders_group_command(void *ctx, uint16_t group) noexcept;
void openttd_orders_delete_backup(void *ctx) noexcept;
void openttd_orders_clear_backup_gui(uint32_t tile, uint32_t user) noexcept;
void openttd_orders_clear_backup_post(uint32_t user) noexcept;
void openttd_orders_missing_aircraft_orders(void *ctx) noexcept;
void openttd_orders_change_timetable_command(void *ctx, uint8_t index, uint8_t field, uint16_t value) noexcept;
uint64_t openttd_rust_orders_start_tick(int32_t, int32_t, uint16_t, uint64_t);
int32_t openttd_rust_orders_start_date(uint64_t, int32_t, uint16_t, uint64_t);
OpenTTDConsistState *openttd_rust_consist_new();
void openttd_rust_consist_delete(OpenTTDConsistState *);
void openttd_rust_consist_copy(OpenTTDConsistState *, const OpenTTDConsistState *);
void openttd_rust_consist_reset(OpenTTDConsistState *);
OpenTTDVehicleOrderState *openttd_rust_vehicle_orders_new();
void openttd_rust_vehicle_orders_delete(OpenTTDVehicleOrderState *);
OpenTTDOrderListState *openttd_rust_orderlist_new();
void openttd_rust_orderlist_delete(OpenTTDOrderListState *);
OpenTTDOrderBackupState *openttd_rust_orderbackup_new();
void openttd_rust_orderbackup_delete(OpenTTDOrderBackupState *);
OpenTTDOrderVector *openttd_rust_order_vector_new(void (*)(void *, size_t) noexcept, void (*)(void *, size_t) noexcept);
void openttd_rust_order_vector_delete(OpenTTDOrderVector *);
size_t openttd_rust_order_vector_size(const OpenTTDOrderVector *);
OpenTTDOrderFields *openttd_rust_order_vector_data(const OpenTTDOrderVector *);
void openttd_rust_order_vector_resize(OpenTTDOrderVector *, size_t);
void openttd_rust_order_vector_insert(OpenTTDOrderVector *, size_t, const void *);
void openttd_rust_order_vector_erase(OpenTTDOrderVector *, size_t);
void openttd_rust_order_vector_move(OpenTTDOrderVector *, size_t, size_t);
void openttd_rust_order_vector_assign(OpenTTDOrderVector *, const void *, size_t);
/* C++ establishes Order/DestinationID lifetimes in Rust-allocated cells.
 * Trivial destruction precedes freeing/replacing their allocation. */
void openttd_orders_construct(void *, size_t) noexcept;
void openttd_orders_destroy(void *, size_t) noexcept;
}
const OpenTTDOrdersLeaves &GetRustOrdersLeaves();
#endif /* RUST_ORDERS_FFI_H */
