/* This file is part of OpenTTD and is licensed under the GNU General Public License version 2. */
/** @file aircraft-boundary.hpp Strict native fixture defaults for the direct aircraft ABI. */
#ifndef OPENTTD_AIRCRAFT_BOUNDARY_HPP
#define OPENTTD_AIRCRAFT_BOUNDARY_HPP
#include "rust/aircraft_ffi.h"
#include <cstdlib>
#include <cstdio>
/* Every function pointer is valid. A fixture explicitly supplies every service
 * it expects to use, so an unexpected crossing fails instead of silently passing. */
template <typename T> struct AircraftUnexpectedService;
template <typename R, typename... A> struct AircraftUnexpectedService<R (OPENTTD_AIRCRAFT_CALL *)(A...)> {
	static R OPENTTD_AIRCRAFT_CALL Call(A...) noexcept { std::abort(); }
};
static OpenTTDAircraftLeaves AircraftTestLeaves()
{
	OpenTTDAircraftLeaves leaves{};
	leaves.subtype = AircraftUnexpectedService<decltype(leaves.subtype)>::Call;
	leaves.x = AircraftUnexpectedService<decltype(leaves.x)>::Call;
	leaves.set_x = AircraftUnexpectedService<decltype(leaves.set_x)>::Call;
	leaves.y = AircraftUnexpectedService<decltype(leaves.y)>::Call;
	leaves.set_y = AircraftUnexpectedService<decltype(leaves.set_y)>::Call;
	leaves.z = AircraftUnexpectedService<decltype(leaves.z)>::Call;
	leaves.set_z = AircraftUnexpectedService<decltype(leaves.set_z)>::Call;
	leaves.tile = AircraftUnexpectedService<decltype(leaves.tile)>::Call;
	leaves.set_tile = AircraftUnexpectedService<decltype(leaves.set_tile)>::Call;
	leaves.direction = AircraftUnexpectedService<decltype(leaves.direction)>::Call;
	leaves.set_direction = AircraftUnexpectedService<decltype(leaves.set_direction)>::Call;
	leaves.tick_counter = AircraftUnexpectedService<decltype(leaves.tick_counter)>::Call;
	leaves.set_tick_counter = AircraftUnexpectedService<decltype(leaves.set_tick_counter)>::Call;
	leaves.owner = AircraftUnexpectedService<decltype(leaves.owner)>::Call;
	leaves.vehicle_status = AircraftUnexpectedService<decltype(leaves.vehicle_status)>::Call;
	leaves.set_vehicle_status = AircraftUnexpectedService<decltype(leaves.set_vehicle_status)>::Call;
	leaves.current_speed = AircraftUnexpectedService<decltype(leaves.current_speed)>::Call;
	leaves.set_current_speed = AircraftUnexpectedService<decltype(leaves.set_current_speed)>::Call;
	leaves.subspeed = AircraftUnexpectedService<decltype(leaves.subspeed)>::Call;
	leaves.set_subspeed = AircraftUnexpectedService<decltype(leaves.set_subspeed)>::Call;
	leaves.progress = AircraftUnexpectedService<decltype(leaves.progress)>::Call;
	leaves.set_progress = AircraftUnexpectedService<decltype(leaves.set_progress)>::Call;
	leaves.acceleration = AircraftUnexpectedService<decltype(leaves.acceleration)>::Call;
	leaves.maximum_speed = AircraftUnexpectedService<decltype(leaves.maximum_speed)>::Call;
	leaves.set_maximum_speed = AircraftUnexpectedService<decltype(leaves.set_maximum_speed)>::Call;
	leaves.set_breakdown_counter = AircraftUnexpectedService<decltype(leaves.set_breakdown_counter)>::Call;
	leaves.order_type = AircraftUnexpectedService<decltype(leaves.order_type)>::Call;
	leaves.order_destination = AircraftUnexpectedService<decltype(leaves.order_destination)>::Call;
	leaves.running_ticks = AircraftUnexpectedService<decltype(leaves.running_ticks)>::Call;
	leaves.set_running_ticks = AircraftUnexpectedService<decltype(leaves.set_running_ticks)>::Call;
	leaves.order_time = AircraftUnexpectedService<decltype(leaves.order_time)>::Call;
	leaves.set_order_time = AircraftUnexpectedService<decltype(leaves.set_order_time)>::Call;
	leaves.day_counter = AircraftUnexpectedService<decltype(leaves.day_counter)>::Call;
	leaves.set_day_counter = AircraftUnexpectedService<decltype(leaves.set_day_counter)>::Call;
	leaves.profit = AircraftUnexpectedService<decltype(leaves.profit)>::Call;
	leaves.set_profit = AircraftUnexpectedService<decltype(leaves.set_profit)>::Call;
	leaves.last_station = AircraftUnexpectedService<decltype(leaves.last_station)>::Call;
	leaves.set_last_station = AircraftUnexpectedService<decltype(leaves.set_last_station)>::Call;
	leaves.set_economy_service = AircraftUnexpectedService<decltype(leaves.set_economy_service)>::Call;
	leaves.set_calendar_service = AircraftUnexpectedService<decltype(leaves.set_calendar_service)>::Call;
	leaves.set_breakdowns = AircraftUnexpectedService<decltype(leaves.set_breakdowns)>::Call;
	leaves.set_reliability = AircraftUnexpectedService<decltype(leaves.set_reliability)>::Call;
	leaves.set_cargo_age = AircraftUnexpectedService<decltype(leaves.set_cargo_age)>::Call;
	leaves.next = AircraftUnexpectedService<decltype(leaves.next)>::Call;
	leaves.map_size_x = AircraftUnexpectedService<decltype(leaves.map_size_x)>::Call;
	leaves.map_max_x = AircraftUnexpectedService<decltype(leaves.map_max_x)>::Call;
	leaves.map_max_y = AircraftUnexpectedService<decltype(leaves.map_max_y)>::Call;
	leaves.plane_speed = AircraftUnexpectedService<decltype(leaves.plane_speed)>::Call;
	leaves.no_jetcrash = AircraftUnexpectedService<decltype(leaves.no_jetcrash)>::Call;
	leaves.plane_crashes = AircraftUnexpectedService<decltype(leaves.plane_crashes)>::Call;
	leaves.service_at_helipad = AircraftUnexpectedService<decltype(leaves.service_at_helipad)>::Call;
	leaves.disaster_sound = AircraftUnexpectedService<decltype(leaves.disaster_sound)>::Call;
	leaves.economy_date = AircraftUnexpectedService<decltype(leaves.economy_date)>::Call;
	leaves.calendar_date = AircraftUnexpectedService<decltype(leaves.calendar_date)>::Call;
	leaves.station = AircraftUnexpectedService<decltype(leaves.station)>::Call;
	leaves.airport_tile = AircraftUnexpectedService<decltype(leaves.airport_tile)>::Call;
	leaves.station_tile = AircraftUnexpectedService<decltype(leaves.station_tile)>::Call;
	leaves.rotation = AircraftUnexpectedService<decltype(leaves.rotation)>::Call;
	leaves.airport_width = AircraftUnexpectedService<decltype(leaves.airport_width)>::Call;
	leaves.airport_height = AircraftUnexpectedService<decltype(leaves.airport_height)>::Call;
	leaves.airport_type = AircraftUnexpectedService<decltype(leaves.airport_type)>::Call;
	leaves.station_owner = AircraftUnexpectedService<decltype(leaves.station_owner)>::Call;
	leaves.has_hangar = AircraftUnexpectedService<decltype(leaves.has_hangar)>::Call;
	leaves.has_airport = AircraftUnexpectedService<decltype(leaves.has_airport)>::Call;
	leaves.airport_fta = AircraftUnexpectedService<decltype(leaves.airport_fta)>::Call;
	leaves.airport_blocks = AircraftUnexpectedService<decltype(leaves.airport_blocks)>::Call;
	leaves.had_vehicle = AircraftUnexpectedService<decltype(leaves.had_vehicle)>::Call;
	leaves.dummy_airport = AircraftUnexpectedService<decltype(leaves.dummy_airport)>::Call;
	leaves.airport_elements = AircraftUnexpectedService<decltype(leaves.airport_elements)>::Call;
	leaves.helipads = AircraftUnexpectedService<decltype(leaves.helipads)>::Call;
	leaves.airport_flags = AircraftUnexpectedService<decltype(leaves.airport_flags)>::Call;
	leaves.airport_delta_z = AircraftUnexpectedService<decltype(leaves.airport_delta_z)>::Call;
	leaves.node = AircraftUnexpectedService<decltype(leaves.node)>::Call;
	leaves.fta = AircraftUnexpectedService<decltype(leaves.fta)>::Call;
	leaves.moving = AircraftUnexpectedService<decltype(leaves.moving)>::Call;
	leaves.engine_speed = AircraftUnexpectedService<decltype(leaves.engine_speed)>::Call;
	leaves.engine_subtype = AircraftUnexpectedService<decltype(leaves.engine_subtype)>::Call;
	leaves.engine_sound = AircraftUnexpectedService<decltype(leaves.engine_sound)>::Call;
	leaves.engine_reliability = AircraftUnexpectedService<decltype(leaves.engine_reliability)>::Call;
	leaves.vehicle_type = AircraftUnexpectedService<decltype(leaves.vehicle_type)>::Call;
	leaves.slope = AircraftUnexpectedService<decltype(leaves.slope)>::Call;
	leaves.tile_height = AircraftUnexpectedService<decltype(leaves.tile_height)>::Call;
	leaves.airport_entry = AircraftUnexpectedService<decltype(leaves.airport_entry)>::Call;
	leaves.direction_towards = AircraftUnexpectedService<decltype(leaves.direction_towards)>::Call;
	leaves.new_position = AircraftUnexpectedService<decltype(leaves.new_position)>::Call;
	leaves.hangar_height = AircraftUnexpectedService<decltype(leaves.hangar_height)>::Call;
	leaves.terminal_count = AircraftUnexpectedService<decltype(leaves.terminal_count)>::Call;
	leaves.hangar_exit = AircraftUnexpectedService<decltype(leaves.hangar_exit)>::Call;
	leaves.can_use_station = AircraftUnexpectedService<decltype(leaves.can_use_station)>::Call;
	leaves.service_interval = AircraftUnexpectedService<decltype(leaves.service_interval)>::Call;
	leaves.needs_service = AircraftUnexpectedService<decltype(leaves.needs_service)>::Call;
	leaves.chain_in_depot = AircraftUnexpectedService<decltype(leaves.chain_in_depot)>::Call;
	leaves.waiting_unbunching = AircraftUnexpectedService<decltype(leaves.waiting_unbunching)>::Call;
	leaves.nearest_depot_order = AircraftUnexpectedService<decltype(leaves.nearest_depot_order)>::Call;
	leaves.part_of_orders = AircraftUnexpectedService<decltype(leaves.part_of_orders)>::Call;
	leaves.next_station = AircraftUnexpectedService<decltype(leaves.next_station)>::Call;
	leaves.next_aircraft = AircraftUnexpectedService<decltype(leaves.next_aircraft)>::Call;
	leaves.random = AircraftUnexpectedService<decltype(leaves.random)>::Call;
	leaves.update_position = AircraftUnexpectedService<decltype(leaves.update_position)>::Call;
	leaves.rotor_image = AircraftUnexpectedService<decltype(leaves.rotor_image)>::Call;
	leaves.copy_sprite = AircraftUnexpectedService<decltype(leaves.copy_sprite)>::Call;
	leaves.position_viewport = AircraftUnexpectedService<decltype(leaves.position_viewport)>::Call;
	leaves.create_effect = AircraftUnexpectedService<decltype(leaves.create_effect)>::Call;
	leaves.dirty_start_stop = AircraftUnexpectedService<decltype(leaves.dirty_start_stop)>::Call;
	leaves.play_sound = AircraftUnexpectedService<decltype(leaves.play_sound)>::Call;
	leaves.truncate_cargo = AircraftUnexpectedService<decltype(leaves.truncate_cargo)>::Call;
	leaves.crash_news = AircraftUnexpectedService<decltype(leaves.crash_news)>::Call;
	leaves.station_rating = AircraftUnexpectedService<decltype(leaves.station_rating)>::Call;
	leaves.landing_rating = AircraftUnexpectedService<decltype(leaves.landing_rating)>::Call;
	leaves.free_order = AircraftUnexpectedService<decltype(leaves.free_order)>::Call;
	leaves.service_in_depot = AircraftUnexpectedService<decltype(leaves.service_in_depot)>::Call;
	leaves.leave_unbunching = AircraftUnexpectedService<decltype(leaves.leave_unbunching)>::Call;
	leaves.dirty_depot = AircraftUnexpectedService<decltype(leaves.dirty_depot)>::Call;
	leaves.first_arrival = AircraftUnexpectedService<decltype(leaves.first_arrival)>::Call;
	leaves.begin_loading = AircraftUnexpectedService<decltype(leaves.begin_loading)>::Call;
	leaves.dirty_details = AircraftUnexpectedService<decltype(leaves.dirty_details)>::Call;
	leaves.update_delta = AircraftUnexpectedService<decltype(leaves.update_delta)>::Call;
	leaves.touchdown_animation = AircraftUnexpectedService<decltype(leaves.touchdown_animation)>::Call;
	leaves.destination_too_far = AircraftUnexpectedService<decltype(leaves.destination_too_far)>::Call;
	leaves.delete_range_news = AircraftUnexpectedService<decltype(leaves.delete_range_news)>::Call;
	leaves.handle_breakdown = AircraftUnexpectedService<decltype(leaves.handle_breakdown)>::Call;
	leaves.handle_loading = AircraftUnexpectedService<decltype(leaves.handle_loading)>::Call;
	leaves.service_order = AircraftUnexpectedService<decltype(leaves.service_order)>::Call;
	leaves.dummy_order = AircraftUnexpectedService<decltype(leaves.dummy_order)>::Call;
	leaves.age_vehicle = AircraftUnexpectedService<decltype(leaves.age_vehicle)>::Call;
	leaves.economy_age = AircraftUnexpectedService<decltype(leaves.economy_age)>::Call;
	leaves.decrease_value = AircraftUnexpectedService<decltype(leaves.decrease_value)>::Call;
	leaves.check_orders = AircraftUnexpectedService<decltype(leaves.check_orders)>::Call;
	leaves.check_breakdown = AircraftUnexpectedService<decltype(leaves.check_breakdown)>::Call;
	leaves.running_cost = AircraftUnexpectedService<decltype(leaves.running_cost)>::Call;
	leaves.subtract_cost = AircraftUnexpectedService<decltype(leaves.subtract_cost)>::Call;
	leaves.dirty_lists = AircraftUnexpectedService<decltype(leaves.dirty_lists)>::Call;
	leaves.next_stopping_station = AircraftUnexpectedService<decltype(leaves.next_stopping_station)>::Call;
	leaves.remove_depot_orders = AircraftUnexpectedService<decltype(leaves.remove_depot_orders)>::Call;
	leaves.assert_flying = AircraftUnexpectedService<decltype(leaves.assert_flying)>::Call;
	leaves.invalid_movement = AircraftUnexpectedService<decltype(leaves.invalid_movement)>::Call;
	leaves.invalid_position = AircraftUnexpectedService<decltype(leaves.invalid_position)>::Call;
	leaves.invalid_scheme = AircraftUnexpectedService<decltype(leaves.invalid_scheme)>::Call;
	leaves.unreachable = AircraftUnexpectedService<decltype(leaves.unreachable)>::Call;
	leaves.speed_property = AircraftUnexpectedService<decltype(leaves.speed_property)>::Call;
	leaves.cargo_age_property = AircraftUnexpectedService<decltype(leaves.cargo_age_property)>::Call;
	leaves.range_property = AircraftUnexpectedService<decltype(leaves.range_property)>::Call;
	leaves.start_sound = AircraftUnexpectedService<decltype(leaves.start_sound)>::Call;
	leaves.touchdown_sound = AircraftUnexpectedService<decltype(leaves.touchdown_sound)>::Call;
	leaves.rotor_image_if_changed = AircraftUnexpectedService<decltype(leaves.rotor_image_if_changed)>::Call;
	leaves.update_rotor_image = AircraftUnexpectedService<decltype(leaves.update_rotor_image)>::Call;
	leaves.process_orders = AircraftUnexpectedService<decltype(leaves.process_orders)>::Call;
	leaves.enter_depot = AircraftUnexpectedService<decltype(leaves.enter_depot)>::Call;
	leaves.vehicle_crash = AircraftUnexpectedService<decltype(leaves.vehicle_crash)>::Call;
	leaves.delete_aircraft = AircraftUnexpectedService<decltype(leaves.delete_aircraft)>::Call;
	leaves.send_to_depot = AircraftUnexpectedService<decltype(leaves.send_to_depot)>::Call;
	leaves.sample_count = AircraftUnexpectedService<decltype(leaves.sample_count)>::Call;
	leaves.helicopter_sound = AircraftUnexpectedService<decltype(leaves.helicopter_sound)>::Call;
	leaves.explosion_sound = AircraftUnexpectedService<decltype(leaves.explosion_sound)>::Call;
	leaves.skid_sound = AircraftUnexpectedService<decltype(leaves.skid_sound)>::Call;
	leaves.ticks_per_year = AircraftUnexpectedService<decltype(leaves.ticks_per_year)>::Call;
	leaves.fta_blocks = AircraftUnexpectedService<decltype(leaves.fta_blocks)>::Call;
	leaves.fta_heading = AircraftUnexpectedService<decltype(leaves.fta_heading)>::Call;
	leaves.fta_next_position = AircraftUnexpectedService<decltype(leaves.fta_next_position)>::Call;
	leaves.fta_next = AircraftUnexpectedService<decltype(leaves.fta_next)>::Call;
	leaves.block_node = AircraftUnexpectedService<decltype(leaves.block_node)>::Call;
	leaves.route_node = AircraftUnexpectedService<decltype(leaves.route_node)>::Call;
	leaves.block_choice = AircraftUnexpectedService<decltype(leaves.block_choice)>::Call;
	return leaves;
}
#endif /* OPENTTD_AIRCRAFT_BOUNDARY_HPP */
