# Narrow first Windows mode: native VS2022 MSVC, Ninja, static release CRT.
# This runs before any game/test/generator target is created (CMP0091 NEW).
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows" OR CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "Windows Rust requires native Windows; cross-OS builds are unsupported")
endif()
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR
   MSVC_VERSION LESS 1930 OR NOT MSVC_VERSION LESS 1950)
    message(FATAL_ERROR "Windows Rust requires VS 2022 MSVC; Clang, MinGW and other compilers are unsupported")
endif()
if(NOT CMAKE_GENERATOR STREQUAL "Ninja")
    message(FATAL_ERROR "Windows Rust requires single-config Ninja")
endif()
if(NOT CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo" OR NOT OPTION_USE_ASSERTS)
    message(FATAL_ERROR "Windows Rust requires RelWithDebInfo and OPTION_USE_ASSERTS=ON; Debug and other modes are unsupported")
endif()
if(HOST_BINARY_DIR)
    message(FATAL_ERROR "Windows Rust does not support external HOST_BINARY_DIR configurations")
endif()
if(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL "MultiThreaded")
    message(FATAL_ERROR "Windows Rust requires CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded (/MT); dynamic and debug CRTs are unsupported")
endif()
foreach(RUST_CPP_FLAGS CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_INIT CMAKE_CXX_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT)
    separate_arguments(RUST_CPP_ARGUMENTS WINDOWS_COMMAND "${${RUST_CPP_FLAGS}}")
    foreach(RUST_CPP_ARGUMENT IN LISTS RUST_CPP_ARGUMENTS)
        if(RUST_CPP_ARGUMENT MATCHES "^[-/]M(Dd?|Td)$")
            message(FATAL_ERROR "Windows Rust refuses conflicting CRT flags in ${RUST_CPP_FLAGS}; use the MSVC runtime property")
        endif()
    endforeach()
endforeach()
foreach(RUST_LINK_FLAGS CMAKE_EXE_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO)
    separate_arguments(RUST_LINK_ARGUMENTS WINDOWS_COMMAND "${${RUST_LINK_FLAGS}}")
    foreach(RUST_LINK_ARGUMENT IN LISTS RUST_LINK_ARGUMENTS)
        string(TOUPPER "${RUST_LINK_ARGUMENT}" RUST_LINK_ARGUMENT_UPPER)
        if(RUST_LINK_ARGUMENT_UPPER MATCHES "^[-/](NODEFAULTLIB|FORCE)(:|$)")
            message(FATAL_ERROR "Windows Rust refuses CRT mismatch suppression in ${RUST_LINK_FLAGS}")
        endif()
    endforeach()
endforeach()
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded CACHE STRING "Windows Rust static release CRT")
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(RUST_WINDOWS_TARGET i686-pc-windows-msvc)
    set(RUST_WINDOWS_ARCH_CHECK "defined(_M_IX86) && !defined(_M_X64) && !defined(_M_ARM64)")
    set(RUST_WINDOWS_TRIPLET x86-windows-static)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(RUST_WINDOWS_TARGET x86_64-pc-windows-msvc)
    set(RUST_WINDOWS_ARCH_CHECK "defined(_M_X64) && !defined(_M_ARM64)")
    set(RUST_WINDOWS_TRIPLET x64-windows-static)
else()
    message(FATAL_ERROR "Windows Rust supports only x86 and x64 pointer widths")
endif()
if(VCPKG_TARGET_TRIPLET AND NOT VCPKG_TARGET_TRIPLET STREQUAL RUST_WINDOWS_TRIPLET)
    message(FATAL_ERROR "Windows Rust requires ${RUST_WINDOWS_TRIPLET}, not ${VCPKG_TARGET_TRIPLET}")
endif()
